type = "card"
title = "Education"
description = "My academic journey."

[[items]]
title = "PhD in Computer Science"
subtitle = "Zhejiang University"
date = "2026 - Present"
content = "State Key Lab of CAD&CG. Advisors: Prof. Chunhua Shen and Prof. Hao Chen."

[[items]]
title = "BSc in Computer Science and Technology"
subtitle = "Zhejiang University"
date = "2022 - 2026 (expected)"
content = "Chu Kochen Honors College, Mixed Class."
