type = "card"
title = "奖项"
description = "我获得的荣誉与奖项。"

[[items]]
title = "浙江省政府奖学金"
subtitle = "浙江省政府"
date = "2025"
content = "因学业成绩优异获得。"

[[items]]
title = "浙江省政府奖学金"
subtitle = "浙江省政府"
date = "2024"
content = "因学业成绩优异获得。"

[[items]]
title = "二等奖学金"
subtitle = "浙江大学"
date = "2023"
content = "因学业成绩优秀获得。"
